name: build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.06.x
          - 4.14.x
          - 5.4.x
        exclude:
          - os: windows-latest
            ocaml-compiler: 4.06.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Set-up Binaryen
        if: ${{ matrix.ocaml-compiler != '4.06.x' }}
        uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ${{ github.token }}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os == 'ubuntu-latest' }}

      - run: opam install . --with-test

      - run: opam install wasm_of_ocaml-compiler
        if: ${{ matrix.ocaml-compiler != '4.06.x' }}

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam exec -- dune build @runtest-wasm
        if: ${{ matrix.ocaml-compiler != '4.06.x' }}

      - run: opam exec -- git diff --exit-code

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml 4.14.x
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
          dune-cache: true

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v3
